# This file was generated by the {rix} R package v0.16.0 on 2025-12-04
# with following call:
# >rix(date = "2025-12-02",
#  > r_pkgs = required_packages,
#  > system_pkgs = c("quarto",
#  > "git",
#  > "pandoc",
#  > "typst",
#  > "stanc",
#  > "tbb",
#  > "gettext",
#  > "libintl"),
#  > git_pkgs = list(list(package_name = "onsets",
#  > repo_url = "https://gitlab.com/jlverissimo/onsets",
#  > commit = "184858760cd63fb039c74492ad8f85bb0465e80a")),
#  > tex_pkgs = c("amsmath",
#  > "ninecolors",
#  > "apa7",
#  > "scalerel",
#  > "threeparttable",
#  > "threeparttablex",
#  > "endfloat",
#  > "environ",
#  > "multirow",
#  > "tcolorbox",
#  > "pdfcol",
#  > "tikzfill",
#  > "fontawesome5",
#  > "framed",
#  > "newtx",
#  > "fontaxes",
#  >      "xstring",
#  > "wrapfig",
#  > "tabularray",
#  > "siunitx",
#  > "fvextra",
#  > "geometry",
#  > "setspace",
#  > "fancyvrb",
#  > "anyfontsize"),
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-12-02.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      collapse
      cowplot
      easystats
      ggokabeito
      ggrain
      glmmTMB
      here
      itsadug
      marginaleffects
      mgcv
      patchwork
      quarto
      scales
      tidybayes
      tidygam
      tidyverse
      tinytable
      transformr
      webshot2;
  };
 
    onsets = (pkgs.rPackages.buildRPackage {
      name = "onsets";
      src = pkgs.fetchgit {
        url = "https://gitlab.com/jlverissimo/onsets";
        rev = "184858760cd63fb039c74492ad8f85bb0465e80a";
        sha256 = "sha256-vRgUfHre8ie1S3TiHXo9itI1BK2fFTVwodrFqpBMHh4=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          doSNOW
          foreach
          mgcv
          progress
          snow;
      };
    });
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      anyfontsize
      apa7
      endfloat
      environ
      fancyvrb
      fontawesome5
      fontaxes
      framed
      fvextra
      geometry
      multirow
      newtx
      ninecolors
      pdfcol
      scalerel
      setspace
      siunitx
      tabularray
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      wrapfig
      xstring;
  });
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      gettext
      git
      glibcLocales
      libintl
      nix
      pandoc
      positron-bin
      quarto
      R
      stanc
      tbb
      typst
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ onsets rpkgs tex  system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
