project:
  title: "Web 2 Lab - Stage 1 RR"
  render:
    - web2lab-RR_stage1.qmd

site-url: "https://jgeller112.github.io/Webcam2Lab-VWP/"

csl: apa.csl

format:

  preprint-docx:
    output-file: web2lab-RR_stage1.docx

  preprint-typst:
    wordcount: true
    line-number: true
    include-before-body:
      - text: "#show <refs>: set par(hanging-indent: 1.4em)"
  html: 
    theme: cosmo
    toc: true
    mainfont: Fira Sans
    toc-depth: 2
    toc-title: "Manuscript Outline"
    toc-location: right
    code-tools: true
    code-fold: true
    code-summary: "Show R code"
    execute:
      echo: true

comments:
  hypothesis: true
