project:
  title: "Web 2 Lab - Stage 1 RR"
  render:
    - web2lab-RR_stage1.qmd

site-url: "https://jgeller112.github.io/Webcam2Lab-VWP/"

language: 
  citation-last-author-separator: "and"
  citation-masked-author: "Masked Citation"
  citation-masked-date: "n.d."
  citation-masked-title: "Masked Title"
  email: "drjasongeller@gmail.com"
  title-block-author-note: "Author Note"
  title-block-correspondence-note: "Correspondence concerning this article should be addressed to"
  title-block-role-introduction: "Author roles were classified using the Contributor Role Taxonomy (CRediT; https://credit.niso.org/) as follows:"
  csl: https://www.zotero.org/styles/apa

format:

  preprint-docx:
    output-file: web2lab-RR_stage1.docx

  preprint-typst:
    wordcount: true
    line-number: true
    include-before-body:
      - text: "#show <refs>: set par(hanging-indent: 1.4em)"
  html: 
    theme: cosmo
    toc: true
    mainfont: Fira Sans
    toc-depth: 2
    toc-title: "Manuscript Outline"
    toc-location: right
    code-tools: true
    code-fold: true
    code-summary: "Show R code"
    execute:
      echo: true

comments:
  hypothesis: true
